export type Difficulty = 'easy' | 'medium' | 'hard';

export const HUNGARIAN_WORDS = {
  easy: ["Kutya", "Macska", "Autó", "Ház", "Fa", "Nap", "Hold", "Virág", "Labda", "Szék", "Asztal", "Ajtó", "Ablak", "Alma", "Körte", "Hal", "Madár", "Pók", "Kígyó", "Béka", "Szem", "Száj", "Orr", "Fül", "Kéz", "Láb", "Haj", "Kalap", "Sapka", "Sál", "Kesztyű", "Zokni", "Póló", "Szoknya", "Ruha", "Ágy", "Párna", "Takaró", "Bögre", "Pohár", "Tányér", "Kanál", "Villa", "Kés", "Fazék", "Serpenyő", "Tűz", "Víz", "Föld", "Kő", "Fű", "Levél", "Felhő", "Eső", "Hó", "Jég", "Csillag", "Szív", "Doboz", "Táska", "Könyv", "Füzet", "Ceruza", "Toll", "Radír", "Vonalzó", "Olló", "Ragasztó", "Festék", "Ecset", "Kréta", "Tábla", "Szivacs", "Kuka", "Seprű", "Lapát", "Rongy", "Vödör", "Szappan", "Törölköző", "Fésű", "Kefe", "Tükör", "Fogkefe", "Fogkrém", "Sampon", "Tusfürdő", "Parfüm", "Rúzs", "Körömlakk", "Gyűrű", "Nyaklánc", "Fülbevaló", "Karkötő", "Óra", "Szemüveg", "Napszemüveg", "Esernyő", "Pénztárca", "Kulcs"],
  medium: ["Elefánt", "Repülőgép", "Hajó", "Bicikli", "Telefon", "Pizza", "Hamburger", "Fényképezőgép", "Cipő", "Nadrág", "Televízió", "Rádió", "Gitár", "Zongora", "Robot", "Torta", "Fagylalt", "Lufi", "Sárkány", "Majom", "Pingvin", "Zsiráf", "Zebra", "Oroszlán", "Tigris", "Medve", "Farkas", "Róka", "Nyúl", "Mókus", "Egér", "Patkány", "Denevér", "Bagoly", "Sas", "Papagáj", "Hattyú", "Kacsa", "Liba", "Tyúk", "Kakas", "Malac", "Tehén", "Ló", "Bárány", "Kecske", "Szamár", "Teve", "Kenguru", "Koala", "Panda", "Gorilla", "Csimpánz", "Delfin", "Bálna", "Cápa", "Polip", "Rák", "Kagyló", "Csiga", "Hernyó", "Pillangó", "Méh", "Darázs", "Hangya", "Szöcske", "Tücsök", "Katicabogár", "Szúnyog", "Légy", "Bogár", "Gomba", "Makk", "Toboz", "Gesztenye", "Dió", "Mogyoró", "Mandula", "Eper", "Málna", "Szeder", "Áfonya", "Cseresznye", "Meggy", "Szilva", "Barack", "Sárgabarack", "Dinnye", "Szőlő", "Banán", "Narancs", "Citrom", "Kivi", "Ananász", "Mangó", "Papaya", "Kókusz", "Gránátalma", "Füge", "Datolya"],
  hard: ["Számítógép", "Tündér", "Boszorkány", "Lovag", "Királylány", "Űrhajó", "Dinoszaurusz", "Krokodil", "Mikrohullámú sütő", "Helikopter", "Tengeralattjáró", "Mikroszkóp", "Távcső", "Ejtőernyő", "Szélmalom", "Mosógép", "Hűtőszekrény", "Kalóz", "Vár", "Bolygó", "Űrhajós", "Idegen", "Szörny", "Vámpír", "Vérfarkas", "Zombi", "Szellem", "Csontváz", "Múmia", "Sárkánygyík", "Unikornis", "Pegazus", "Kentaur", "Sellő", "Küklopsz", "Minotaurusz", "Medúza", "Szfinx", "Főnix", "Griff", "Sárkányhajó", "Kalózhajó", "Kincsesláda", "Térkép", "Iránytű", "Horgony", "Kormánykerék", "Ágyú", "Kard", "Pajzs", "Íj", "Nyíl", "Lándzsa", "Bárd", "Buzogány", "Sisak", "Páncél", "Korona", "Jogar", "Trón", "Kastély", "Palota", "Torony", "Híd", "Kapu", "Fal", "Árok", "Börtön", "Kút", "Szökőkút", "Szobor", "Emlékmű", "Templom", "Katedrális", "Mecset", "Zsinagóga", "Piramis", "Obeliszk", "Kolosszeum", "Akropolisz", "Stonehenge", "Eiffel-torony", "Szabadság-szobor", "Taj Mahal", "Kínai Nagy Fal", "Pisai ferde torony", "Big Ben", "Tower Bridge", "Golden Gate híd", "Sydney-i Operaház", "Mount Rushmore", "Grand Canyon", "Niagara-vízesés", "Mount Everest", "Vezúv", "Fuji", "Kilimandzsáró", "Szahara", "Amazonas", "Tűzhányó"]
};

export const ENGLISH_WORDS = {
  easy: ["Dog", "Cat", "Car", "House", "Tree", "Sun", "Moon", "Flower", "Ball", "Chair", "Table", "Door", "Window", "Apple", "Pear", "Fish", "Bird", "Spider", "Snake", "Frog", "Eye", "Mouth", "Nose", "Ear", "Hand", "Foot", "Hair", "Hat", "Cap", "Scarf", "Glove", "Sock", "T-shirt", "Skirt", "Dress", "Bed", "Pillow", "Blanket", "Mug", "Glass", "Plate", "Spoon", "Fork", "Knife", "Pot", "Pan", "Fire", "Water", "Earth", "Stone", "Grass", "Leaf", "Cloud", "Rain", "Snow", "Ice", "Star", "Heart", "Box", "Bag", "Book", "Notebook", "Pencil", "Pen", "Eraser", "Ruler", "Scissors", "Glue", "Paint", "Brush", "Chalk", "Board", "Sponge", "Trash can", "Broom", "Shovel", "Rag", "Bucket", "Soap", "Towel", "Comb", "Hairbrush", "Mirror", "Toothbrush", "Toothpaste", "Shampoo", "Shower gel", "Perfume", "Lipstick", "Nail polish", "Ring", "Necklace", "Earring", "Bracelet", "Watch", "Glasses", "Sunglasses", "Umbrella", "Wallet", "Key"],
  medium: ["Elephant", "Airplane", "Boat", "Bicycle", "Phone", "Pizza", "Hamburger", "Camera", "Shoe", "Pants", "Television", "Radio", "Guitar", "Piano", "Robot", "Cake", "Ice cream", "Balloon", "Kite", "Monkey", "Penguin", "Giraffe", "Zebra", "Lion", "Tiger", "Bear", "Wolf", "Fox", "Rabbit", "Squirrel", "Mouse", "Rat", "Bat", "Owl", "Eagle", "Parrot", "Swan", "Duck", "Goose", "Hen", "Rooster", "Pig", "Cow", "Horse", "Sheep", "Goat", "Donkey", "Camel", "Kangaroo", "Koala", "Panda", "Gorilla", "Chimpanzee", "Dolphin", "Whale", "Shark", "Octopus", "Crab", "Shell", "Snail", "Caterpillar", "Butterfly", "Bee", "Wasp", "Ant", "Grasshopper", "Cricket", "Ladybug", "Mosquito", "Fly", "Beetle", "Mushroom", "Acorn", "Pinecone", "Chestnut", "Walnut", "Hazelnut", "Almond", "Strawberry", "Raspberry", "Blackberry", "Blueberry", "Cherry", "Sour cherry", "Plum", "Peach", "Apricot", "Melon", "Grape", "Banana", "Orange", "Lemon", "Kiwi", "Pineapple", "Mango", "Papaya", "Coconut", "Pomegranate", "Fig", "Date"],
  hard: ["Computer", "Fairy", "Witch", "Knight", "Princess", "Spaceship", "Dinosaur", "Crocodile", "Microwave", "Helicopter", "Submarine", "Microscope", "Telescope", "Parachute", "Windmill", "Washing machine", "Refrigerator", "Pirate", "Castle", "Planet", "Astronaut", "Alien", "Monster", "Vampire", "Werewolf", "Zombie", "Ghost", "Skeleton", "Mummy", "Dragon", "Unicorn", "Pegasus", "Centaur", "Mermaid", "Cyclops", "Minotaur", "Medusa", "Sphinx", "Phoenix", "Griffin", "Longship", "Pirate ship", "Treasure chest", "Map", "Compass", "Anchor", "Steering wheel", "Cannon", "Sword", "Shield", "Bow", "Arrow", "Spear", "Axe", "Mace", "Helmet", "Armor", "Crown", "Scepter", "Throne", "Palace", "Tower", "Bridge", "Gate", "Wall", "Moat", "Prison", "Well", "Fountain", "Statue", "Monument", "Temple", "Cathedral", "Mosque", "Synagogue", "Pyramid", "Obelisk", "Colosseum", "Acropolis", "Stonehenge", "Eiffel Tower", "Statue of Liberty", "Taj Mahal", "Great Wall of China", "Leaning Tower of Pisa", "Big Ben", "Tower Bridge", "Golden Gate Bridge", "Sydney Opera House", "Mount Rushmore", "Grand Canyon", "Niagara Falls", "Mount Everest", "Mount Vesuvius", "Mount Fuji", "Mount Kilimanjaro", "Sahara Desert", "Amazon River", "Volcano"]
};

export function getRandomWord(lang: 'hu' | 'en', difficulty: Difficulty): string {
  const words = lang === 'hu' ? HUNGARIAN_WORDS[difficulty] : ENGLISH_WORDS[difficulty];
  const randomIndex = Math.floor(Math.random() * words.length);
  return words[randomIndex];
}
